# Generated by Django 5.2.4 on 2025-07-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('heures_CM', models.IntegerField()),
                ('heures_TP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sigle', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoursAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.anneeacademique')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.cours')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours_enseignes', to='gestion_academique.enseignant')),
            ],
            options={
                'unique_together': {('cours', 'annee', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.IntegerField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.departement')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionAnnuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.anneeacademique')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.promotion')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_responsables', to='gestion_academique.enseignant')),
            ],
            options={
                'unique_together': {('promotion', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('DESINSCRIT', 'Désinscrit'), ('DIPLOME', 'Diplômé')], default='ACTIF', max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.etudiant')),
                ('promotion_annuelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.promotionannuelle')),
            ],
            options={
                'unique_together': {('etudiant', 'promotion_annuelle')},
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_tp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_interro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, max_length=10)),
                ('session', models.CharField(choices=[('NORMALE', 'Session normale'), ('RATTRAPAGE', 'Session de rattrapage')], max_length=20)),
                ('cours_annuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.coursannuel')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_academique.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'cours_annuel', 'session')},
            },
        ),
    ]
